version: "3"
services:
  api:
    container_name: todo-api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    command: uvicorn main:app --host "0.0.0.0" --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./src/api:/code
  frontend:
    container_name: todo-frontend
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend/todo-app:/app
      - /app/node_modules
